name: debug

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
      id: python

    - name: Set up Clozure Common Lisp
      run: |
        mkdir -p /opt/ccl
        wget -c https://github.com/Clozure/ccl/releases/download/v1.12.1/ccl-1.12.1-linuxx86.tar.gz -O - | tar xz -C /opt/ccl/
        ln -s /opt/ccl/lx86cl64 /usr/local/bin/ccl64

    - name: Checkout uhppoted-dll
      run: git clone https://github.com/uhppoted/uhppoted-dll.git ../uhppoted-dll
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Miscellaneous stuff
      run: |
        pip install yapf
        sudo apt-get install rlwrap

    - name: Build
      run: make build-debug
