name: debug

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
      id: python

    - name: Checkout uhppoted-dll
      run: git clone https://github.com/uhppoted/uhppoted-dll.git ../uhppoted-dll
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        pip install yapf
        make build-debug
