name: debug

on:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        compiler: [clang]

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Checkout uhppoted-dll
      run: git clone https://github.com/uhppoted/uhppoted-dll.git ../uhppoted-dll
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make build
        make cpp
