name: ltsc

on:
  workflow_dispatch:  
  push:
    branches: [ windows-2019-ltsc ]
  pull_request:
    branches: [ windows-2019-ltsc ]

jobs:

  build:
    name: Build Windows 2019 DLL
    runs-on: windows-2019
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Upload Windows 2019 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uhppoted-dll-windows-2019
        path: lib
